# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'openAPI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for openAPI
  pod 'Alamofire', '~> 4.4'
  pod 'SwiftyXMLParser'

  target 'openAPITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'openAPIUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
